# Rewrites install names of bundled dependencies in an installed macOS tree to use @rpath, and adds
# run paths to the executables and libraries in the tree. Set BUNDLE_PREFIX, BUNDLE_BIN_DIR,
# BUNDLE_LIB_DIR, OTOOL, and INSTALL_NAME_TOOL before including this file or running it with
# `cmake -P`. Set CODESIGN to re-sign each modified file.
cmake_minimum_required(VERSION 3.28)

set(_bin_dir "${BUNDLE_PREFIX}/${BUNDLE_BIN_DIR}")
set(_lib_dir "${BUNDLE_PREFIX}/${BUNDLE_LIB_DIR}")
file(GLOB _lib_entries RELATIVE "${_lib_dir}" "${_lib_dir}/*.dylib")
file(GLOB _bin_files "${_bin_dir}/*")
file(GLOB _lib_files "${_lib_dir}/*.dylib")

function(_bundle_fixup file rpath is_library)
  if(IS_SYMLINK "${file}" OR IS_DIRECTORY "${file}")
    return()
  endif()
  execute_process(
    COMMAND "${OTOOL}" -L "${file}"
    OUTPUT_VARIABLE _deps
    RESULT_VARIABLE _result)
  if(NOT _result EQUAL 0)
    return()
  endif()
  set(_id "")
  if(is_library)
    execute_process(COMMAND "${OTOOL}" -D "${file}" OUTPUT_VARIABLE _id)
    string(REGEX MATCH "[^\n]+\n?$" _id "${_id}")
    string(STRIP "${_id}" _id)
  endif()
  set(_args)
  string(REGEX MATCHALL "\t[^\t\n]+ \\(compatibility" _lines "${_deps}")
  foreach(_line IN LISTS _lines)
    string(REGEX REPLACE "^\t(.+) \\(compatibility$" "\\1" _dep "${_line}")
    get_filename_component(_leaf "${_dep}" NAME)
    if(NOT _dep STREQUAL _id
       AND NOT _dep MATCHES "^(@|/usr/lib/|/System/)"
       AND _leaf IN_LIST _lib_entries)
      list(APPEND _args -change "${_dep}" "@rpath/${_leaf}")
    endif()
  endforeach()
  if(is_library)
    if(_id)
      get_filename_component(_leaf "${_id}" NAME)
    else()
      get_filename_component(_leaf "${file}" NAME)
    endif()
    if(NOT _id STREQUAL "@rpath/${_leaf}")
      list(APPEND _args -id "@rpath/${_leaf}")
    endif()
  endif()
  execute_process(COMMAND "${OTOOL}" -l "${file}" OUTPUT_VARIABLE _load_commands)
  string(FIND "${_load_commands}" "path ${rpath} (offset" _rpath_index)
  if(_rpath_index EQUAL -1)
    list(APPEND _args -add_rpath "${rpath}")
  endif()
  if(NOT _args)
    return()
  endif()
  message(STATUS "Rewriting install names: ${file}")
  execute_process(COMMAND "${INSTALL_NAME_TOOL}" ${_args} "${file}" COMMAND_ERROR_IS_FATAL ANY)
  if(CODESIGN)
    execute_process(COMMAND "${CODESIGN}" --force --sign - "${file}" COMMAND_ERROR_IS_FATAL ANY)
  endif()
endfunction()

file(RELATIVE_PATH _lib_from_bin "${_bin_dir}" "${_lib_dir}")
foreach(_file IN LISTS _bin_files)
  _bundle_fixup("${_file}" "@executable_path/${_lib_from_bin}" FALSE)
endforeach()
foreach(_file IN LISTS _lib_files)
  _bundle_fixup("${_file}" "@loader_path" TRUE)
endforeach()
